### PR TITLE
add phpseclib support for RSA encryption

### PR DESCRIPTION
**Pull request by nfinkelstein**
We've had trouble with openssl_pkey_get_private() and openssl_pkey_get_public() functions occasionally not recognizing well-formatted public and private keys, for reasons that are difficult to track down.  To circumvent the need for these functions, we've allowed for phpseclib support of the RSA algorithms.  The code is written according to the style and architecture of the existing library, and is fully tested.  It will have no effect on existing code (i.e. it does not change the public API).

### CODE REVIEW

**Comment by nfinkelstein** [comment]
@cirpo Thanks for the comments - made all requested changed.  I'm not sure what you mean by: 

> I would add phpseclib in the vendor through composer: https://packagist.org/packages/phpseclib/phpseclib and not moving the actual classes.

phpseclib was already in the composer.json file, and so is already being loaded by composer through packagist.

**Comment by cirpo** [comment]
@nfinkelstein oh... lol, my bad ! Thanks for the changes, I will let you know

**Comment by nfinkelstein** [comment]
@cirpo 

Thanks.  Do you have any estimate of when you might get to this?

**Comment by cirpo** [comment]
@nfinkelstein we are going to do a final check next week, in the meantime could you please rebase? thanks

**Comment by nfinkelstein** [comment]
@cirpo 

Thanks.  I've rebased the changes.

**Comment by cirpo** [comment]
@nfinkelstein I would like to merge it tomorrow, but it seems that I can't merge it now to master, could you please rebase it again?

**Comment by nfinkelstein** [comment]
Thanks - rebased again.

**Comment by cirpo** [comment]
@nfinkelstein one last thing, could you please update the README as well with the seclib examples? 
Then we are really good to go :)

**Comment by nfinkelstein** [comment]
@cirpo 

Thanks - added section to readme on SecLib usage.

**Comment by nfinkelstein** [comment]
@cirpo 

Thanks!

**Comment by cirpo** [comment]
@nfinkelstein I'm going to create a new tag in a bit

**Comment by cirpo** [comment]
btw, @nfinkelstein thank you!

**Comment by cirpo** [comment]
tag 3.0.0 created

**Pull request merged**
