### PR TITLE
CS fix

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Symfony doesn't allow commenting out code and that's the code style you've indicated you wanted in the .styleci.yml config file.

Symfony recommends simply deleting code, since we have git if we need it back.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
See #66 to address the travis issue.

**Comment by cirpo** [comment]
@GrahamCampbell I had to force pushed master as the tag 6.0.4 had one issue, could you please rebase your PR with master? thanks

**Comment by GrahamCampbell** [comment]
Done.

**Comment by cirpo** [comment]
thanks

**Pull request merged**
