### PR TITLE
Don't cast -1 (error) to true (valid signature)

### PR DESCRIPTION
**Pull request by kelunik**
And please add a security contact address.

### CODE REVIEW

**Comment by cirpo** [comment]
@odino fine for me.

**Comment by odino** [comment]
:+1: @cirpo can you merge and tag?

**Comment by cirpo** [comment]
@odino yes, can I also merge https://github.com/namshi/jose/pull/59 and create a tag from this two PRs?

**Comment by odino** [comment]
yep

On Wed, Dec 9, 2015 at 12:01 PM, cirpo <notifications@github.com> wrote:

> @odino <https://github.com/odino> yes, can I also merge #59
> <https://github.com/namshi/jose/pull/59> and create a tag from this two
> PRs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/namshi/jose/pull/58#issuecomment-163145043>.
>



-- 
Nadalin Alessandro
http://www.linkedin.com/in/alessandronadalin
www.odino.org
www.twitter.com/_odino_

**Pull request merged**
