### PR TITLE
A few fixes to support phpseclib 2

### PR DESCRIPTION
**Pull request by foreachlt**
@cirpo Wondered if this dependency could be upgraded? I feel like I fixed the broken bits and the tests pass :shipit: :wink: 

Thanks.

### CODE REVIEW

**Comment by cirpo** [comment]
@foreachlt  thanks, I'll give it a look this week. I'm a little bit worried and we should triple check because probably there are some cases not covered by tests (we already tried once).

**Comment by foreachlt** [comment]
@cirpo thank you for taking a look at this :+1:

**Comment by tristanbes** [comment]
we're really looking towards this merge/fix because without this, we can't use google api client in version 2 because it requires phpseclib2 which conflicts with your library

**Comment by cirpo** [comment]
@foreachlt could you please rebase this PR with the latest master? We've just released version 6.0.4. 
thanks

**Comment by foreachlt** [comment]
@cirpo will do :wink:

**Comment by cirpo** [comment]
@foreachlt if you could use php-cs-fixer with `--level=symfony --fixers=ordered_use` it would be awesome :)

**Comment by foreachlt** [comment]
@cirpo it should be all done :+1:

**Comment by foreachlt** [comment]
@cirpo ohh, will apply php fixer stuff too, just a sec

**Comment by cirpo** [comment]
@foreachlt @tristanbes I will try to make it by this week, thanks a lot guys!

**Comment by foreachlt** [comment]
@cirpo php-cs-fixer hasn't found any violations in `src/` dir :wink:

**Comment by cirpo** [comment]
@foreachlt :+1:

**Comment by tristanbes** [comment]
@cirpo what prevents this PR to be merged and tag a release right now if all the tests pass? I'm curious.

**Comment by cirpo** [comment]
@tristanbes last time the tests where passing but someone experienced some issues. We need to check the coverage. I can't do it right now as I'm a bit busy and I would avoid the same mistake we did last time.
If you desperately need it you can point your composer.json to https://github.com/foreachlt/jose 
It's just a matter of precaution and time :)
I'll try to do it as soon as possible, I promise :)

**Comment by tristanbes** [comment]
ok thanks for your anwser :)

**Comment by cirpo** [comment]
@foreachlt  I created a new branch phpseclib-2 https://github.com/namshi/jose/tree/phpseclib-2. Could you please open the PR against that branch? I will be easy for everyone to test it, wdyt?

**Comment by cirpo** [comment]
@foreachlt @tristanbes everything seems working fine on our side.

@foreachlt you get phpseclib ~2.0 the 2.0-dev version, what if we specify the 2.0.0? what are your thoughts about it?

**Comment by foreachlt** [comment]
@cirpo sure, I agree with you. I didn't realize it would get `2.0-dev`. What do you think about `2.0.*` in order to accept minor patches by default? Provided that semver is used correctly by phpseclib-2 :)

**Comment by tristanbes** [comment]
:+1:  for `2.0.*`

**Comment by cirpo** [comment]
@foreachlt if you want you can open the PR against master :)
I will merge it and create the 6.1.0 tag

**Comment by foreachlt** [comment]
@cirpo changed the version. Rebased, tests still pass locally. All good to :shipit: I think :wink:

**Comment by cirpo** [comment]
yalla, lets merge!

**Comment by cirpo** [comment]
@foreachlt  @tristanbes enjoy the 6.1.0 release

thanks a lot folks!

**Pull request merged**
