### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by fredroo**

### CODE REVIEW

**Comment by odino** [comment]
Hi @fredroo, what is this PR supposed to change?

**Comment by Spomky** [comment]
IMHO, this is a regression as it will limit phpseclib <2.1

**Comment by odino** [comment]
@Spomky agreed -- just want to be sure we hear back from the author this time, else I'll close it just like the other PR

**Comment by Spomky** [comment]
@odino I think you can close this issue

**Pull request closed without merging**
