### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by fredroo**

### CODE REVIEW

**Comment by Spomky** [comment]
Should be closed. The proposed modification is not valid.

**Comment by GrahamCampbell** [comment]
👎 This PR is wrong.

**Comment by odino** [comment]
So much hate on this PR :smile: let's chill!

@fredroo I dont think this PR does what's intended to do -- can you tell us what you were trying to achieve? Also, all PRs must pass on travis-ci.

Cheers!

**Comment by GrahamCampbell** [comment]
> So much hate on this PR 😄 let's chill!

Not hating on anyone. Just downvoting the PR. Nothing more, and nothing less.

**Comment by odino** [comment]
There are ways and ways to say things -- so we should always be considerate when giving feedback to anyone in public. I'd suggest a more lenient approach ;-)

**Comment by odino** [comment]
Closed for inactivity

**Pull request closed without merging**
