### PR TITLE
CS fixes

### PR DESCRIPTION
**Pull request by kbond**
(Continuation of #48)

I added https://styleci.io/ config and the bridge for php-cs-fixer. I would suggest adding this repo to style-ci and future PR's can be checked for style issues automatically. Style issues can be fixed in accordance with this projects style guide simply by running `php-cs-fixer fix .` in the repo root directory.

If you would like to change the style requirements for this project, let me know (https://styleci.readme.io/docs/presets and https://styleci.readme.io/docs/fixers). 

I also removed `composer.lock` as it was causing issues with travis. It isn't recommended to have this in library repos.

### CODE REVIEW

**Comment by cirpo** [comment]
@kbond wow! I didn't know about  https://styleci.io/, thanks.
what could be the issues having the `composer.lock` file in the library repo? I feel much safer having it, especially because it's a a lib about securing things. 
With the composer.lock, other than having a specific version locked, you also have the specific dependency commit which can assure you that  even if the version is removed you still know where to point to. wdyt?

**Comment by kbond** [comment]
The `composer.lock` is ignored unless you are working with the root project - development or testing only. See https://getcomposer.org/doc/02-libraries.md#lock-file for more information. Basically, it is ignored for everyone using this library.

Also see: https://travis-ci.org/namshi/jose/jobs/94175923 - the build failed because dependencies couldn't be resolved. This is because the lock file prevented installing valid deps.

**Comment by cirpo** [comment]
@kbond thanks for the explanation, I didn't know the composer.lock wasn't take into account if it's inside another project but I still think it's fine for the project itself: correct me if I'm wrong but from the link you posted, thanks to the composer.lock we now know that in order to install styleci.io we have to drop support for PHP 5.4, right?
Dropping support for PHP 5.4 could be fine, but still I can see the benefit of having the composer.lock file so now we know that.
Am I missing something, what do you think?

**Comment by kbond** [comment]
For end applications, is very important for `composer.lock` to be commited. It ensures your deps are identical for all developers and environments.

The styleci library is compatible with 5.4 and even 5.3 I think. The library requires the Symfony Console component at either 2.0+ or 3.0+. Symfony 2.0 requires PHP 5.3+ but Symfony 3.0 requires 5.5+. The problem with he failed build is the lock file. When it was generated last (by me in my development env) I was using php 5.5 so it was locked as 5.5+. The travis PHP env 5.5, 5.6, 7.0 worked fine because it used Symfony 3.0 but when it tried to resolve the deps for the PHP 5.4 env it failed because Symfony was locked at 3.0 which requires PHP 5.5. When I removed the lock file, it resolved fine to Symfony 2.x as expected.

I hope I am making sense. Let me know if you would like me to explain further.

**Comment by cirpo** [comment]
@kbond yes, it makes sense :) 
And it's exactly my point: I would keep the composer.lock and act accordingly updating the minimum PHP version.
wdyt?
If you do that, could you also please squash the commits? thanks a lot!

**Comment by kbond** [comment]
You want me to make the requirement for this lib 5.5+?

**Comment by kbond** [comment]
I just want to clarify - the styleci.co service just requires the `.styleci` file (this isn't even required, really). When style errors are found, the service gives you the option to open PR's to fix them. Additionally, new PRs are automatically checked for errors.

I added the `sllh/php-cs-fixer-styleci-bridge` dev dep and the `.phpcs` file as a helper for developers to run `php-cs-fixer` before they create a PR to quickly fix their style issues.

If you really want to keep the `composer.lock` file, there are three options:

1. Increase the PHP requirement to 5.5+ (I **strongly** advise against this as all users running PHP 5.4 would lose the ability to use this library simply because we added a dev requirement...)
2. Remove the `sllh/php-cs-fixer-styleci-bridge` dep and `.phpcs` file.
3. Change travis to use `composer update` instead of `composer install` (this will allow you to keep the composer.lock file and PHP 5.4)

Option 3 is probably the best of both worlds but I really don't understand your argument for keeping the `composer.lock`. No major libraries have it committed because of the exact issue I had in this PR. The lock file would be updated in virtually every PR opened on said library!

https://github.com/symfony/symfony
https://github.com/laravel/framework
https://github.com/thephpleague/flysystem
https://github.com/ircmaxell/password_compat
https://github.com/guzzle/guzzle

**Comment by cirpo** [comment]
PHP 5.4 is not supported anymore: http://php.net/supported-versions.php
and we could bump the jose version to mark to fact that we support PHP >= 5.5
My argument was about the fact that it happened in the past we had issues with semantic versioning because some dependencies were breaking the lib/project, that's why I'm a bit scared of removing the composer.lock . @odino wdyt?

**Comment by kbond** [comment]
Changing the min requirement to 5.5 because 5.4 isn't supported I don't agree with but I can understand. I just didn't want you to change it because a dev dependency wouldn't resolve...

**Comment by cirpo** [comment]
@kbond thank you for your time and sorry for the delay in replying to you. I thought about that and I think it's fine to remove the composer.lock, if we need to "lock" a version for an external dependency we will specify the version in the composer.json (as we do for phpseclib).

Could you please squash the commits into one? thanks

**Comment by kbond** [comment]
Re-based and squashed.

**Comment by kbond** [comment]
After merge, if you want to use styleci - you should enable it for this repo. All future PRs will be checked for style issues. They have a badge for the readme also.

**Comment by cirpo** [comment]
thanks!

**Pull request merged**
